#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mono.Samples.Snake.Resource", IsApplication=true)]

namespace Mono.Samples.Snake
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int tileSize = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int greenstar = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int redstar = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int yellowstar = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int snake = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int snake_layout = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int text = 2130903042;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int snake_layout = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int mode_lose_prefix = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int mode_lose_suffix = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int mode_pause = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int mode_ready = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int snake_layout_text_text = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000 }
			public static int[] TileView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int TileView_tileSize = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
