#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NotePad.Resource", IsApplication=true)]

namespace NotePad
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int opaque_blue = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int transparent_green = 2130771969;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int large_font_size = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int standard_border = 2130837505;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int body = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int confirm = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int text1 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int title = 2130968579;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050001
			public const int notes_list = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int notes_row = 2131034114;
			
			// aapt resource value: 0x7F050000
			public const int note_edit = 2131034112;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int body = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int confirm = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int edit_note = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int menu_delete = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int menu_insert = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int no_notes = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int title = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int BaseText = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int SmallText = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
